Lecture 1 Start

In [ ]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

np.__version__

'2.2.5'

In [7]:
a = np.array([1, 2, 3, 4])
a, type(a), a.shape, a.ndim

(array([1, 2, 3, 4]), numpy.ndarray, (4,), 1)

In [ ]:
a = np.array((1, 2, 3, 4))
a, type(a), a.shape, a.ndim #using tuples result is same

In [ ]:
#0-dimension
a = np.array(2)

a, type(a), a.shape, a.ndim #scalar value does not have shape or dimension

(array(2), numpy.ndarray, (), 0)

In [12]:
#2-dimension

a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a, type(a), a.shape, a.ndim

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 numpy.ndarray,
 (2, 4),
 2)

In [14]:
#3-dimension --> List/vector of 2d list/vector
a = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]],[[1, 2, 3, 4],[5, 6, 7, 8]]])

a, type(a), a.shape, a.ndim


(array([[[1, 2, 3, 4],
         [5, 6, 7, 8]],
 
        [[1, 2, 3, 4],
         [5, 6, 7, 8]]]),
 numpy.ndarray,
 (2, 2, 4),
 3)

Lecture 1 End

Lecture 2 Start

In [ ]:
# 1d array
a = np.array([1, 2, 3, 4])

print(a[3])
print(a[-1]) #get last value
print(a[-2]) #get second last value

4
4
3


In [29]:
#2d array
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(a[0][1])
print(a[0,1]) #print 2d vector/array
print(a[0,-1], a[1, -1])

2
2
4 8


In [38]:
a = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]],
              [[1, 2, 3, 4],[5, 6, 7, 8]]])

print(a[1][0])
print(a[1][0][3])
print(a[1,:,3])
print(a[1,:,1:3])


[1 2 3 4]
4
[4 8]
[[2 3]
 [6 7]]


Lecture 2 End

Lecture 3 Start

In [43]:
a = np.array([1, 2, 3, 4.0])
a, a.dtype, a.shape

(array([1., 2., 3., 4.]), dtype('float64'), (4,))

In [ ]:
a = np.array(['apple', 'banana', 'pineapple']) #here u9 or u6 means max chars in any item in the list
a

array(['apple', 'banana', 'pineapple'], dtype='<U9')

In [47]:
a = np.array(['apple', 'banana', 'pineapple'], dtype='S')
a

array([b'apple', b'banana', b'pineapple'], dtype='|S9')

In [55]:
a = np.array(['0', '1', '2'], dtype='i4')
a

array([0, 1, 2], dtype=int32)

In [70]:
#a = np.array(['0.0', '1.0', '2.0'], dtype='i4')
a = np.array(['0.0', '1.0', '2.0'], dtype='f')
b = a.astype('i')
b.astype('bool')
b

#float string will not convert into integer directly but we need to convert into integer

array([0, 1, 2], dtype=int32)

In [ ]:
a = np.array(['12', '3', '24', '1'])
a.sort()
a #sort in asc order

array(['1', '12', '24', '3'], dtype='<U2')

In [93]:
a = np.array([12,3,24,1])
a = np.sort(a)[::-1] #sort in desc order by slicing
a
b = a[::-1]
b

array([ 1,  3, 12, 24])

In [97]:
# slicing practice
lst = [10, 20, 30, 40, 50, 60, 70]
print(lst[::3])

[10, 40, 70]


Lecture 3 End

Lecture 4 Start - npnan & npinf

In [7]:
print(np.nan == np.nan)

False


In [10]:
a = np.nan
b = np.nan

a,b

a==b, a>b, a<b #cannot compare nan

(False, False, False)

In [13]:
a = np.inf
b = np.inf

a, b

(inf, inf)

In [14]:
a==b, a<b, a>b #can compare inf

(True, False, False)

In [21]:
a = np.array([[1,2,3],[4,5,6]], dtype='float')
a.shape, a.dtype

((2, 3), dtype('float64'))

In [23]:
a[0][1] = np.nan
a[0][2] = np.inf
a
#we can assign nan only when dtype is float, not int

array([[ 1., nan, inf],
       [ 4.,  5.,  6.]])

In [25]:
np.isnan(a)

array([[False,  True, False],
       [False, False, False]])

In [26]:
np.isinf(a)

array([[False, False,  True],
       [False, False, False]])

Lecture 4 Ends


Lecture 5 start - statistical operation

In [28]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

a.mean(), np.mean(a), np.mean([1, 2, 3, 4, 5, 6, 7])

(np.float64(4.0), np.float64(4.0), np.float64(4.0))

In [33]:
b = a.var() #variance
c = a.std() #standard deviation
d = np.median(a) #median
b,c, d

(np.float64(4.0), np.float64(2.0), np.float64(4.0))

In [34]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[11, 22, 33, 44, 55, 66, 77]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [35]:
a.mean(), np.mean(a), np.std(a), a.std(), a.var(), np.median(a)

(np.float64(24.0),
 np.float64(24.0),
 np.float64(25.37715508089904),
 np.float64(25.37715508089904),
 np.float64(644.0),
 np.float64(9.0))

Lecture 5 ends

Lecture 6 start - Shape, Reshape, Ravel, Flatten

In [36]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[11, 22, 33, 44, 55, 66, 77]])
a.ndim, a.shape

(2, (2, 7))

In [41]:
a.reshape(1, 14) #while reshaping multiplication of both should be equal, 1*14, 2*7
a.reshape(1,-1) #take 1 rows and as many cols you want

array([[ 1,  2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55, 66, 77]])

In [42]:
a.ravel() #automatically converts into 1d array

array([ 1,  2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55, 66, 77])

In [43]:
a.flatten() #diff between flatten and ravel, flatten returns only a view but ravel returns orignal
# flatten returns a copy, ravel returns orignal

array([ 1,  2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55, 66, 77])

Lecture 6 ends

Lecture 7 start - Random, linspace, range, random, zeros, ones, tile, repeat

In [47]:
np.arange(1, 5, dtype='float')

array([1., 2., 3., 4.])

In [64]:
np.arange(1, 11, 2, dtype='float') #you can control the difference but cannot controls values you get

array([1., 3., 5., 7., 9.])

In [63]:
np.linspace(1, 11, 11) #you can control how many numbers you want but cannot control difference between values

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [65]:
from numpy import random

In [73]:
random.rand(1,10), random.randint(1,10)

(array([[0.24227717, 0.46676493, 0.56050444, 0.76848068, 0.23358849,
         0.65521804, 0.88652139, 0.65596689, 0.92009561, 0.85189454]]),
 3)

In [78]:
np.array(range(1, 10)) # ref from for i in range(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.zeros([2, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
np.ones([5, 5, 4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [87]:
np.tile([1,2,3],20)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [88]:
np.repeat([1,2,3],20)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Lecture 7 ends

Lecture 8 start - Where

In [92]:
index = np.where(a>10)
a[index]

array([11, 22, 33, 44, 55, 66, 77])

In [94]:
np.where(a>50, 0, a) # if true, replace with 0 else with a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44,  0,  0,  0]])

In [97]:
a.max()

(np.int64(77), np.int64(13))

In [99]:
a.argmax() #this produces stacked version of array hence we cannot do a[13]
# so we flatten it

np.int64(13)

In [103]:
a[13]

IndexError: index 13 is out of bounds for axis 0 with size 2

In [107]:
a.flatten()[13], a.max()

(np.int64(77), np.int64(77))

In [108]:
a.argmin()

np.int64(0)

In [109]:
a.flatten()[0], a.max()

(np.int64(1), np.int64(77))

Lecture 8 ends

Lecture 9 start - Numpy Array Read and Write

In [110]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [111]:
np.save('np_array', a, False)

In [119]:
np.savetxt('np_array_txt', a, delimiter=',', header='hello')

In [121]:
b = np.array([a,a])
b, b.ndim

(array([[[ 1,  2,  3,  4,  5,  6,  7],
         [11, 22, 33, 44, 55, 66, 77]],
 
        [[ 1,  2,  3,  4,  5,  6,  7],
         [11, 22, 33, 44, 55, 66, 77]]]),
 3)

In [122]:
np.savetxt('np_array_csv.csv', b, delimiter='^') #we cannot save 3d array in csv file

ValueError: Expected 1D or 2D array, got 3D array instead

In [126]:
np.save('np_array_3d', b)

In [129]:
aa = np.loadtxt('np_array_txt', delimiter=',')
aa

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [11., 22., 33., 44., 55., 66., 77.]])

In [130]:
np.savez('savez', a, b)

In [133]:
d = np.load('savez.npz')

In [134]:
d.files

['arr_0', 'arr_1']

In [136]:
d['arr_0'], d['arr_1']

(array([[ 1,  2,  3,  4,  5,  6,  7],
        [11, 22, 33, 44, 55, 66, 77]]),
 array([[[ 1,  2,  3,  4,  5,  6,  7],
         [11, 22, 33, 44, 55, 66, 77]],
 
        [[ 1,  2,  3,  4,  5,  6,  7],
         [11, 22, 33, 44, 55, 66, 77]]]))

Lecture 9 ends

Lecture 10 start - Concatenation and sorting

In [163]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
c = np.array([32,12,4,1])

np.concatenate([a,b,c])

array([ 1,  2,  3,  4,  3,  4,  5,  6, 32, 12,  4,  1])

In [140]:
x = np.concatenate([a,b,c], axis=-1)
x

array([ 1,  2,  3,  4,  3,  4,  5,  6, 32, 12,  4,  1])

In [152]:
y = np.sort(x)[::-1]
x, y

(array([ 1,  1,  2,  3,  3,  4,  4,  4,  5,  6, 12, 32]),
 array([32, 12,  6,  5,  4,  4,  4,  3,  3,  2,  1,  1]))

In [164]:
b = np.array([a,c])
b, b.ndim

(array([[ 1,  2,  3,  4],
        [32, 12,  4,  1]]),
 2)

In [170]:
a, a.ndim

(array([[ 1,  2,  3,  4],
        [32, 12,  4,  1]]),
 2)

In [ ]:
a = np.array([a,c]) #made a also in same dim to concat

In [168]:
np.concatenate([a,b])

array([[ 1,  2,  3,  4],
       [32, 12,  4,  1],
       [ 1,  2,  3,  4],
       [32, 12,  4,  1]])

In [173]:
np.concatenate([a,b] , axis = 1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [32, 12,  4,  1, 32, 12,  4,  1]])

In [175]:
x = np.vstack([a,b])
x.ndim

2

In [177]:
y = np.hstack([a,b])
y

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [32, 12,  4,  1, 32, 12,  4,  1]])

In [ ]:
arr = np.arange(1,10)
arr = arr.reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])