In [1]:
import numpy as np

In [2]:
a = np.arange(1, 13).reshape(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
b = a[:,2:4]

In [14]:
c = a[1,:]
c[::-1]

array([8, 7, 6, 5])

In [18]:
d = a[0,:]
d, d.ndim

(array([1, 2, 3, 4]), 1)

In [32]:
aa = np.arange(1,7)
aa.reshape(2,3)
aa.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])